spring:
  datasource:
    url: jdbc:mysql:/http://localhost:3306/db
    username: root
    password: pass@word1
  jpa:    hibernate:      ddl-auto: create
    show-sql: true
server:  port: 1234